# Generated by Django 6.0.3 on 2026-03-25 13:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VentasPrepago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Materno')),
                ('curp', models.CharField(max_length=18, validators=[django.core.validators.MinLengthValidator(18)], verbose_name='CURP')),
                ('dn', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Solo se permiten números.'), django.core.validators.MinLengthValidator(10)], verbose_name='DN')),
                ('nip', models.CharField(help_text='Solo se permiten números.', max_length=4, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Solo se permiten números.'), django.core.validators.MinLengthValidator(4)], verbose_name='NIP')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
