# Generated by Django 6.0.3 on 2026-03-25 13:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VentasPrepago',
            new_name='VentaPrepago',
        ),
    ]
