# Generated by Django 6.0.3 on 2026-03-29 00:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_ventaprepago_contact1'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaprepago',
            name='contact2',
            field=models.CharField(default=0, max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Solo se permiten números.'), django.core.validators.MinLengthValidator(10)], verbose_name='CONTACTO 2'),
            preserve_default=False,
        ),
    ]
