# Generated by Django 6.0.3 on 2026-03-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_ventaprepago_contact2'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaprepago',
            name='fvc',
            field=models.DateField(blank=True, null=True, verbose_name='FVC'),
        ),
    ]
