# Generated by Django 6.0.3 on 2026-03-29 04:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_ventaprepago_fvc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaprepago',
            name='apellido_materno',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='APELLIDO MATERNO'),
        ),
        migrations.AlterField(
            model_name='ventaprepago',
            name='fvc',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='FVC'),
            preserve_default=False,
        ),
    ]
