# Generated by Django 6.0.3 on 2026-03-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_ventaprepago_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaprepago',
            name='validada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ventaprepago',
            name='apellido_materno',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='APELLIDO MATERNO'),
        ),
    ]
