# Generated by Django 6.0.3 on 2026-03-29 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_ventaprepago_validada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventaprepago',
            old_name='validada',
            new_name='validar',
        ),
    ]
