# Generated by Django 6.0.3 on 2026-03-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_rename_validada_ventaprepago_validar'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaprepago',
            name='status',
            field=models.CharField(choices=[('en_proceso', 'EN PROCESO'), ('nip_incorrecto', 'NIP INCORRECTO'), ('curp_incorrecto', 'CURP INCORRECTO'), ('sin_fvc', 'SIN FVC'), ('exitosa', 'EXITOSA'), ('baja_exportada', 'BAJA EXPORTADA'), ('alta', 'ALTA'), ('gestionada_por_otro_call_center', 'GESTIONADA POR OTRO CALL CENTER'), ('sin_nip', 'SIN NIP'), ('futura', 'FUTURA'), ('linea_movistar', 'LINEA MOVISTAR'), ('cac_lejano', 'CAC LEJANO')], default='en_proceso', max_length=100, verbose_name='Status'),
        ),
    ]
