# Generated by Django 6.0.3 on 2026-04-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_ventaprepago_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaprepago',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='EMAIL'),
        ),
    ]
