# Generated by Django 6.0.3 on 2026-04-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_ventaprepago_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaprepago',
            name='folio',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='FOLIO'),
        ),
        migrations.AddField(
            model_name='ventaprepago',
            name='usuario_marcador',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='USUARIO MARCADOR'),
        ),
    ]
