# Generated by Django 6.0.3 on 2026-04-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_ventaprepago_folio_ventaprepago_usuario_marcador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaprepago',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='EMAIL'),
        ),
        migrations.AlterField(
            model_name='ventaprepago',
            name='folio',
            field=models.CharField(max_length=100, verbose_name='FOLIO'),
        ),
        migrations.AlterField(
            model_name='ventaprepago',
            name='usuario_marcador',
            field=models.CharField(max_length=100, verbose_name='USUARIO MARCADOR'),
        ),
    ]
