# Generated by Django 6.0.3 on 2026-04-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_alter_ventaprepago_email_alter_ventaprepago_folio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaprepago',
            name='marcador',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='MARCADOR'),
        ),
    ]
