# Generated by Django 6.0.3 on 2026-04-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_ventaprepago_marcador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaprepago',
            name='marcador',
            field=models.CharField(max_length=100, verbose_name='MARCADOR'),
        ),
    ]
