# Generated by Django 6.0.3 on 2026-04-13 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0016_ventaprepago_validador_alter_ventaprepago_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaprepago',
            name='contact1',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16)], verbose_name='CONTACTO 1'),
        ),
    ]
