# Generated by Django 6.0.3 on 2026-04-13 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0017_alter_ventaprepago_contact1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaprepago',
            name='contact1',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Solo se permiten números.'), django.core.validators.MinLengthValidator(10)], verbose_name='CONTACTO 1'),
        ),
    ]
