# Generated by Django 6.0.3 on 2026-04-14 03:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0020_alter_ventaprepago_contact1_alter_ventaprepago_curp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaprepago',
            name='curp',
            field=models.CharField(max_length=18, validators=[django.core.validators.MinLengthValidator(18)], verbose_name='CURP'),
        ),
    ]
