# Generated by Django 6.0.3 on 2026-04-14 03:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0021_alter_ventaprepago_curp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaprepago',
            name='contact1',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator('^\\d{10}\\sAUDIO$')], verbose_name='CONTACTO1'),
        ),
    ]
