# Generated by Django 6.0.3 on 2026-04-14 03:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0022_alter_ventaprepago_contact1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaprepago',
            name='contact1',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator('^[A-Z0-9 ]+$')], verbose_name='CONTACTO1'),
        ),
    ]
