# Generated by Django 6.0.3 on 2026-04-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0023_alter_ventaprepago_contact1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventaprepago',
            name='validar',
        ),
        migrations.AddField(
            model_name='ventaprepago',
            name='acepta_promo',
            field=models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No')], null=True, verbose_name='ACEPTA PROMO'),
        ),
    ]
