# Generated by Django 6.0.3 on 2026-05-17 23:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0025_ventaprepago_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaPospago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='NOMBRE(S)')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='APELLIDO PATERNO')),
                ('apellido_materno', models.CharField(blank=True, default='', max_length=100, verbose_name='APELLIDO MATERNO')),
                ('curp', models.CharField(max_length=18, validators=[django.core.validators.MinLengthValidator(18)], verbose_name='CURP')),
                ('rfc', models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(13)], verbose_name='RFC')),
                ('identifacion', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(15)], verbose_name='IDENTIFICACIÓN')),
                ('dn', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Solo se permiten números.'), django.core.validators.MinLengthValidator(10)], verbose_name='DN')),
                ('nip', models.CharField(help_text='Solo se permiten números.', max_length=4, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Solo se permiten números.'), django.core.validators.MinLengthValidator(4)], verbose_name='NIP')),
                ('contact1', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator('^[A-Z0-9 ]+$')], verbose_name='CONTACTO1')),
                ('contact2', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Solo se permiten números.'), django.core.validators.MinLengthValidator(10)], verbose_name='CONTACTO 2')),
                ('plan', models.CharField(choices=[('pro_8', 'PRO 8'), ('pro_10', 'PRO 10'), ('pro_14', 'PRO 14'), ('pro_18', 'PRO 18'), ('pro_25', 'PRO 25'), ('pro_35', 'PRO 35'), ('pro_ilimitado', 'PRO ILIMITADO')], max_length=20, verbose_name='PLAN')),
                ('cac', models.CharField(max_length=100, verbose_name='CAC')),
                ('cp', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Solo se permiten números.'), django.core.validators.MinLengthValidator(5)], verbose_name='CP')),
                ('fecha_nacimiento', models.DateField(verbose_name='FECHA DE NACIMIENTO')),
                ('estado_republica', models.CharField(choices=[('AGUASCALIENTES', 'AGUASCALIENTES'), ('BAJA CALIFORNIA', 'BAJA CALIFORNIA'), ('BAJA CALIFORNIA SUR', 'BAJA CALIFORNIA SUR'), ('CAMPECHE', 'CAMPECHE'), ('COAHUILA', 'COAHUILA'), ('COLIMA', 'COLIMA'), ('CHIAPAS', 'CHIAPAS'), ('CHIHUAHUA', 'CHIHUAHUA'), ('CIUDAD DE MEXICO', 'CIUDAD DE MEXICO'), ('DURANGO', 'DURANGO'), ('GUANAJUATO', 'GUANAJUATO'), ('GUERRERO', 'GUERRERO'), ('HIDALGO', 'HIDALGO'), ('JALISCO', 'JALISCO'), ('MEXICO', 'MEXICO'), ('MICHOACAN', 'MICHOACAN'), ('MORELOS', 'MORELOS'), ('NAYARIT', 'NAYARIT'), ('NUEVO LEON', 'NUEVO LEON'), ('OAXACA', 'OAXACA'), ('PUEBLA', 'PUEBLA'), ('QUERETARO', 'QUERETARO'), ('QUINTANA ROO', 'QUINTANA ROO'), ('SAN LUIS POTOSI', 'SAN LUIS POTOSI'), ('SINALOA', 'SINALOA'), ('SONORA', 'SONORA'), ('TABASCO', 'TABASCO'), ('TAMAULIPAS', 'TAMAULIPAS'), ('TLAXCALA', 'TLAXCALA'), ('VERACRUZ', 'VERACRUZ'), ('YUCATAN', 'YUCATAN'), ('ZACATECAS', 'ZACATECAS')], max_length=20, verbose_name='ESTADO DE LA REPUBLICA')),
                ('municipio', models.CharField(max_length=100, verbose_name='MUNICIPIO')),
                ('colonia', models.CharField(max_length=100, verbose_name='COLONIA')),
                ('calle', models.CharField(max_length=100, verbose_name='CALLE')),
                ('numero_exterior', models.CharField(max_length=20, verbose_name='NUMERO EXTERIOR')),
                ('numero_interior', models.CharField(blank=True, default='', max_length=20, verbose_name='NUMERO INTERIOR')),
                ('fvc', models.DateField(verbose_name='FVC')),
                ('email', models.EmailField(max_length=254, verbose_name='EMAIL')),
                ('status_pospago', models.CharField(choices=[('en_proceso', 'EN PROCESO'), ('rechazo_nip', 'RECHAZO NIP'), ('rechazo_magento', 'RECHAZO MAGENTO'), ('black_list', 'BLACK LIST'), ('datos_incorrectos', 'DATOS INCORRECTOS'), ('exitosa', 'EXITOSA'), ('linea_movistar', 'LINEA MOVISTAR'), ('gestionada_por_otro_call_center', 'GESTIONADA POR OTRO CALL CENTER'), ('alta', 'ALTA'), ('cancelacion', 'CANCELACIÓN')], default='en_proceso', max_length=100, verbose_name='STATUS')),
            ],
        ),
    ]
