# Generated by Django 6.0.3 on 2026-05-18 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0027_ventapospago_created_ventapospago_supervisor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventapospago',
            old_name='identifacion',
            new_name='identificacion',
        ),
    ]
